options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: maven:3.8.4-jdk-11
    entrypoint: mvn
    args: ["clean", "package"]
    
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "temperature-converter", "--image", "gcr.io/temperatureconverter-sit707/temperature-converter", "--region", "australia-southeast2", "--platform", "managed", "--allow-unauthenticated"]
    
images: ["gcr.io/temperatureconverter-sit707/temperature-converter"]